### PR TITLE
Azhar-day1-confident interval

### PR DESCRIPTION
**Pull request by azhar337**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Exercise
- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Adding GitHub Action capabilities

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by evanyeohboonkhai — CHANGES_REQUESTED** [review]
Hi Azhar, the coding work fine and thanks for the hard work. However there are some feedback I think you can improve in order make the notebook more attractive to the student. 

1. A introduction to the data is need. For example. what is meant by the target value? people with heart disease and without? Can you briefly explain the dataset 
2. Can you embed the  formula  require to calculate the confidence interval? Is not easy to remind formula itself by just referring to the code itself.
3.  Please include the summary, contributor and reference (please follow the demo file structure)
image
4. Please update statsmodels to the environment.yml file
5.  You refer to these two attached link to refer how people discussing the confident interval 
- [https://towardsdatascience.com/illustration-with-python-confidence-interval-ee4736cc3dc2](https://towardsdatascience.com/illustration-with-python-confidence-interval-ee4736cc3dc2)
- [https://towardsdatascience.com/confidence-intervals-with-python-bfa28ebb81c](https://towardsdatascience.com/confidence-intervals-with-python-bfa28ebb81c)
6. It will good that link your notebook the the slide content (example the step, concept, etc)

**Comment by azhar337** [comment]
ok i will adjust the notebook accordingly

**Comment by evanyeohboonkhai** [comment]
@azhar337  Please use backquote to highlight your `variable` names such as `n` , `charlos` and etc. Please check your spelling in your description. Thanks.

**Comment by azhar337** [comment]
ok will readjust that

**Pull request merged**
