### PR TITLE
update 02-0 and 07-0

### PR DESCRIPTION
**Pull request by devenyantis**
02-0_Data Exploration and Data Transformation
- add comments
- add data transformation example

07-0_Decision Tree and Random Forest
- add text classification using decision tree and random forest

### CODE REVIEW

**Comment by kenghooi-teoh** [comment]
**Decision tree**
- adhere to PEP8 style 
`predictions=classifier.predict(X_test)` # add space before and after equal sign
- interpretation on results needed
- explain hyperparameter set for the models (even if we are using the default)
- compare test/train performance
- keep all import statements at the top of the notebook
- print some of the vectorized features to show how they look like


**Data transformation**
- keep all import statements at the top of the notebook
- add a couple of examples on data cleaning (missing data, invalid data, replace values, remove columns)

**Linear Regression ?**

**Comment by devenyantis** [comment]
02-0_Data Exploration and Data Transformation
- PEP8 check
- add handling missing value example
- add range encoding example

07-0_Decision Tree and Random Forest
- PEP8 check
- add default parameters explaination
- add result interpretation

04-1_Linear Regression 2.ipynb
- PEP8 check
- add explanation and result interpretation

04-2_Linear Regression 3.ipynb
- new example using diabetes dataset using raw data
- using preprocessing techniques to prepare data
- PEP8 check

**Comment by kenghooi-teoh** [comment]
**02-0_Data Exploration and Data Transformation**
- For the range encoding, what you applied is called 'binning' / 'quantization'. I believe range encoding refers to something else? (https://en.wikipedia.org/wiki/Range_encoding) 
- better example can be used to illustrate binning, for example something more meaningful would be income in real value range to high/medium/low income groups

**07-0_Decision Tree and Random Forest**
- can we have a visualization of the tree? something similar in (https://medium.com/@rnbrown/creating-and-visualizing-decision-trees-with-python-f8e8fa394176)

**04-1_Linear Regression 2.ipynb**
- I should've said it clearer when i mentioned 'interpretation of results'. What I was expecting is actually the interpretation of the model coefficients :)

**04-2_Linear Regression 3.ipynb**
- it would be nice to have some explanation on the features we are using. What do they represent? Also what are we trying to predict?

**Comment by devenyantis** [comment]
02-0_Data Exploration and Data Transformation

- change range encoding to ordinal variables

07-0_Decision Tree and Random Forest

- add tree view for decision tree and random forest

04-1_Linear Regression 2.ipynb

- add explanation for coefficients

04-2_Linear Regression 3.ipynb

- add dataset description

**Pull request merged**
