### PR TITLE
Bk day3 e2e ds example

### PR DESCRIPTION
**Pull request by evanyeohboonkhai**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New Exercise
- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Adding GitHub Action capabilities

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by jingzhi93 — COMMENTED** [review]
any reason of removing statsmodels lib from environment?

**Review by jingzhi93 — COMMENTED** [review]
did you missed any imports?
image

**Comment by evanyeohboonkhai** [comment]
> any reason of removing statsmodels lib from environment?

I believe I am not remove the statsmodels before, I think some error during merging the cdle2 to this branch cause it does not update here. Solved this issue by adding the statsmodel lib back

**Comment by evanyeohboonkhai** [comment]
> did you missed any imports? image

delete the unwanted command already

**Review by jingzhi93 — APPROVED** [review]

**Pull request merged**
